// infinite/ngx-deview-infinite/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ngx-deview-infinite-app';
  items = [0, 1, 2];
  onAppend() {
    const items = this.items;

    const nextItem = (items[items.length - 1] || 0) + 1;

    this.items = [...items, nextItem];
  }
  trackBy(index: number, item: number): any {
    return item;
  }
}

<style>
  .item {
    padding: 10px;
    border: 1px solid black;
    width: 100%;
  }
</style>
<div NgxDeviewInfinite class="container"
  (append)="onAppend($event)" [options]="{ margin: 5 }" [items]="items">
  <div class="item" *ngFor="let item of items; trackBy: trackBy;">
    Item {{item}}
  </div>
</div>

// infinite/vue-deview-infinite/demo/App.vue
<template>
  <div id="app">
    <deview-infinite className="container" @append="onAppend">
        <div class="item" v-for="item of items" :key="item">Item {{item}}</div>
    </deview-infinite>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { DeviewInfinite } from '../src/index';

@Component({
  components: {
    DeviewInfinite,
  },
})
export default class App extends Vue {
  items = [0, 1, 2];
  onAppend() {
    const items = this.items;
    const nextItem = (items[items.length - 1] || 0) + 1;

    this.items = [...items, nextItem];
  }
}
</script>

<style>
  .item {
    padding: 10px;
    border: 1px solid black;
    width: 100%;
  }
</style>
