// recycle/ngx-deview-recycle/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular';
  items = [];
  num = 0;
  start = 0;
  end = 0;
  onAppend() {
    const items = this.items;

    this.items = [...items, ++this.num];
  }
  shuffle() {
    const items = this.items;

    items.sort(() => Math.random() - 0.5);

    this.items = [...items];
  }
  trackBy(index: number, item: any) {
    return item;
  }
}

<header>
  <p>
    DEVIEW 2019
    <br />
    Cross Framework Component
  </p>
</header>
<div class="list">
  items: {{items.join(", ")}}<br/>
  viisble: <span>{{"{"}} start: {{start}}, end: {{end}} {{"}"}}</span>
</div>
<button class="shuffle" (click)="shuffle()">
  Shuffle
</button>
<div
  NgxDeviewRecycle
  #recycle
  [items]="items"
  [options]="{ margin: 5 }"
  (append)="onAppend()"

  (visibleChange)="start=$event.start;end=$event.end;"
  class="container"
>
  <div class="item" *ngFor="let item of recycle.visibleItems;trackBy: trackBy;">
    Item {{item}}
  </div>
</div>

// recycle/react-deview-recycle/src/App.tsx
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import DeviewRecycle from './react-deview-recycle/DeviewRecycle';
import { findDOMNode } from 'react-dom';


interface AppProps { }
interface AppState {
    name: string;
    list: number[];
}


export default class App extends Component<AppProps, AppState> {
    num = 0;
    constructor(props) {
        super(props);

        this.state = {
            name: "React",
            list: []
        };
    }

    render() {
        return (
            <div>
                <header>
                    <p>
                        DEVIEW 2019
              <br />
                        Cross Framework Component
            </p>
                </header>
                <div className="list">
                    items: {this.state.list.join(", ")} <br />
                    visible: <span id="visible" />
                </div>
                <button className="shuffle" onClick={this.shuffle}>
                    Shuffle
          </button>
                <DeviewRecycle
                    options={{ margin: 5 }}
                    onAppend={this.onAppend}
                    onVisibleChange={this.onVisibleChange}
                    className="container"
                >
                    {this.state.list.map(num => {
                        return (
                            <div className="item" key={num}>
                                Item {num}
                            </div>
                        );
                    })}
                </DeviewRecycle>
            </div>
        );
    }
    onVisibleChange = e => {
        document.querySelector("#visible").innerHTML = `{ start: ${e.start}, end: ${
            e.end
            }}`;
    };
    onAppend = () => {
        const list = this.state.list;

        this.setState({
            list: [...list, ++this.num]
        });
    };
    shuffle = () => {
        const list = this.state.list;

        list.sort(() => Math.random() - 0.5);

        this.setState({
            list: [...list]
        });
    };
}
