// recycle/svelte-deview-recycle/src/DeviewRecycle.svelte
<script>
  import VanillaRecycle from "@egjs/deview-recycle";
  import {
    createEventDispatcher,
    onMount,
    onDestroy,
    tick,
  } from "svelte";

  export let items = [];
  export let start = -1;
  export let end = -1;
  export let container;
  const dispatch = createEventDispatcher();
  let visibleItems = items;
  let recycle;

  const {
    class: className = "",
    itemBy,
    options = {},
    $$slots: slots,
    $$scope: scope,
    ...attributes
  } = $$props;

  delete attributes.items;

  $: syncItems(items);

  function syncItems(items) {
    if (recycle) {
      recycle.beforeSync(items.map(itemBy));
      const indexes = recycle.getRenderingIndexes();

      start = indexes.start;
      end = indexes.end;

      visibleItems = items.slice(start, end + 1);
    } else {
      visibleItems = items;
    }

    tick().then(() => {
      // afterUpdate
      recycle.sync(getChildren());
    });
  }

  function getChildren() {
    return [].slice.call(container.children);
  }
  const callbacks = {};

  onMount(ctx => {
    recycle = new VanillaRecycle(container, {
      ...options,
      renderExternal: true
    })
      .on("append", e => {
        dispatch("append", { ...e });
      })
      .on("visibleChange", e => {
        syncItems(items);
      });

    recycle.beforeSync(items.map(itemBy));
    recycle.sync(getChildren());
  });
  onDestroy(() => {
    recycle.destroy();
  });
</script>

<div class={className} {...attributes} bind:this={container}>
  {#each visibleItems as item, index (itemBy(item, start + index, items)) }
  <slot items={visibleItems} item={item} index={start + index} />
  {/each}
</div>

// recycle/react-deview-recycle/src/react-deview-recycle/DeviewRecycle.tsx
import * as React from "react";
import VanillaRecycle from "@egjs/deview-recycle";
import { RecycleProps } from "./types";
import * as ReactDOM from "react-dom";

export default class DeviewRecycle extends React.PureComponent<RecycleProps> {
    public static defaultProps: Required<RecycleProps> = {
        tag: "div",
        options: {},
        onAppend: () => { },
        onVisibleChange: () => { },
    };
    private recycle!: VanillaRecycle;
    private container!: HTMLElement;

    public render() {
        const props = this.props;
        const Tag = props.tag as any;
        const attributes = { ...props };

        delete attributes.tag;
        delete attributes.options;
        delete attributes.children;

        let visibleChildren: React.ReactElement[] = [];

        if (this.recycle) {
            const children = React.Children.toArray(this.props.children) as React.ReactElement[];
            this.recycle.beforeSync(children.map(child => child.key));

            const indexes = this.recycle.getRenderingIndexes();

            visibleChildren = children.slice(indexes.start, indexes.end + 1);
        }
        return (
            <Tag {...attributes}>{visibleChildren}</Tag>
        );
    }
    public componentDidMount() {
        this.container = ReactDOM.findDOMNode(this) as HTMLElement;
        this.recycle = new VanillaRecycle(
            this.container,
            {
                ...this.props.options,
                renderExternal: true,
            },
        ).on("append", e => {
            this.props.onAppend!({ ...e });
        }).on("visibleChange", e => {
            this.props.onVisibleChange!({ ...e });
            this.forceUpdate();
        });

        this.recycle.sync([].slice.call(this.container.children));
    }
    public componentDidUpdate() {
        this.recycle.sync([].slice.call(this.container.children));
    }
}
